/*
===================================================================
Copyright DHTMLX LTD. http://www.dhtmlx.com
This code is obfuscated and not allowed for any purposes except 
using on sites which belongs to DHTMLX LTD.

Please contact sales@dhtmlx.com to obtain necessary 
license for usage of dhtmlx components.
===================================================================
*/dhtmlXGridObject.prototype.enableUndoRedo=function(){var a=this,b=function(){return a._onEditUndoRedo.apply(a,arguments)};this.attachEvent("onEditCell",b);var e=function(b,c,d){return a._onEditUndoRedo.apply(a,[2,b,c,d?1:0,d?0:1])};this.attachEvent("onCheckbox",e);this._IsUndoRedoEnabled= !0;this._UndoRedoData=[];this._UndoRedoPos= -1};dhtmlXGridObject.prototype.disableUndoRedo=function(){this._IsUndoRedoEnabled= !1;this._UndoRedoData=[];this._UndoRedoPos= -1};dhtmlXGridObject.prototype._onEditUndoRedo=function(a,b,e,f,c){if(this._IsUndoRedoEnabled&&a==2&&c!=f){if(this._UndoRedoPos!== -1&&this._UndoRedoPos!=this._UndoRedoData.length-1)this._UndoRedoData=this._UndoRedoData.slice(0,this._UndoRedoPos+1);else if(this._UndoRedoPos=== -1&&this._UndoRedoData.length>0)this._UndoRedoData=[];var d={old_value:c,new_value:f,bO:b,cell_index:e};this._UndoRedoData.push(d);this._UndoRedoPos++}return!0};dhtmlXGridObject.prototype.doUndo=function(){if(this._UndoRedoPos=== -1)return!1;var a=this._UndoRedoData[this._UndoRedoPos--],b=this.cells(a.bO,a.cell_index);this.abv(a.cell_index)=="tree"?b.setLabel(a.old_value):b.setValue(a.old_value);this.callEvent("onUndo",[a.bO])};dhtmlXGridObject.prototype.doRedo=function(){if(this._UndoRedoPos==this._UndoRedoData.length-1)return!1;var a=this._UndoRedoData[++this._UndoRedoPos];this.cells(a.bO,a.cell_index).setValue(a.new_value);this.callEvent("onUndo",[a.bO])};dhtmlXGridObject.prototype.getRedo=function(){return this._UndoRedoPos==this._UndoRedoData.length-1?[]:this._UndoRedoData.slice(this._UndoRedoPos+1)};dhtmlXGridObject.prototype.getUndo=function(){return this._UndoRedoPos== -1?[]:this._UndoRedoData.slice(0,this._UndoRedoPos+1)};