/*
===================================================================
Copyright DHTMLX LTD. http://www.dhtmlx.com
This code is obfuscated and not allowed for any purposes except 
using on sites which belongs to DHTMLX LTD.

Please contact sales@dhtmlx.com to obtain necessary 
license for usage of dhtmlx components.
===================================================================
*/dhtmlXGridObject.prototype.setRowspan=function(b,d,e){var a=this[this._bfs_cells?"_bfs_cells":"cells"](b,d).cell,c=this.bj[b];if(a.rowSpan&&a.rowSpan!=1)for(var f=c.nextSibling,g=1;g<a.rowSpan;g++){var i=f.childNodes[f.bq[a._cellIndex+1]],h=document.createElement("TD");h.innerHTML="&nbsp;";h._cellIndex=a._cellIndex;h.mG= !0;i?i.parentNode.insertBefore(h,i):f.parentNode.appendChild(h);this._shiftIndexes(f,a._cellIndex,-1);f=f.nextSibling}a.rowSpan=e;for(var c=this._h2?this.bj[this._h2.get[c.idd].parent.bu[this._h2.get[c.idd].index+1].id]:c.nextSibling||this.am[this.am.bP(c)+1],k=[],g=1;g<e;g++){var j=null,j=this.aC&& !this.nh?this._bfs_cells3(c,d).cell:this.cells3(c,d).cell;this._shiftIndexes(c,a._cellIndex,1);j&&j.parentNode.removeChild(j);k.push(c);this._h2?(c=this._h2.get[c.idd].parent.bu[this._h2.get[c.idd].index+1])&&(c=this.bj[c.id]):c=c.nextSibling||this.am[this.am.bP(c)+1]}this.bj[b]._rowSpan=this.bj[b]._rowSpan||{};this.bj[b]._rowSpan[d]=k;this.aC&& !this.nh&&d<this.aC._cCount&&this.aC.setRowspan(b,d,e)};dhtmlXGridObject.prototype._shiftIndexes=function(b,d,e){if(!b.bq){b.bq=[];for(var a=0;a<b.childNodes.length;a++)b.bq[a]=a}for(a=0;a<b.bq.length;a++)a>d&&(b.bq[a]-=e)};dhtmlXGridObject.prototype.enableRowspan=function(){this._erspan= !0;this.enableRowspan=function(){};this.attachEvent("onAfterSorting",function(){if(!this.ic){for(var b=1;b<this.obj.rows.length;b++)if(this.obj.rows[b]._rowSpan){var d=this.obj.rows[b],e;for(e in d._rowSpan)for(var a=d,c=a._rowSpan[e],f=0;f<c.length;f++){a.nextSibling?a.parentNode.insertBefore(c[f],a.nextSibling):a.parentNode.appendChild(c[f]);if(this.aC){var g=this.aC.bj[a.idd],i=this.aC.bj[c[f].idd];g.nextSibling?g.parentNode.insertBefore(i,g.nextSibling):g.parentNode.appendChild(i);this._correctRowHeight(a.idd)}a=a.nextSibling}}var h=this.am.stablesort;this.am=new dhtmlxArray;this.am.stablesort=h;for(b=1;b<this.obj.rows.length;b++)this.am.push(this.obj.rows[b])}});this.attachEvent("onXLE",function(){for(var b=0;b<this.aD.length;b++)for(var d=this.render_row(b),e=d.childNodes,a=0;a<e.length;a++)e[a]._attrs.rowspan&&this.setRowspan(d.idd,a,e[a]._attrs.rowspan)})};